### ISSUE TITLE
User can see their car

### ISSUE THREAD

**Issue by raymondkhoaho** [raymondkhoaho/driving-game#1]
## 💰 Motivation

The user needs to see what they will be controlling.

## 📐 Plan

Put a top-down image of a car on the page.

## ✅ Task List

- [x] Create index.html and styles.css files and link them together
- [x] Add favicon to the head element
- [x] Add a div to hold image of the car
- [x] Ensure that the background and car look formatted correctly
