### ISSUE TITLE
User can turn their car

### ISSUE THREAD

**Issue by raymondkhoaho** [raymondkhoaho/driving-game#2]
## 💰 Motivation

The user needs to be able to control which way their car is facing.

## 📐 Plan

Rotate the image with CSS classes when the user presses an arrow key.

## ✅ Task List

- [x] Create a main.js file and link to index.html to js file
- [x] Create addEventListener for keydown events on the document
- [x] DOM query car image and rotate img (north, south, west, east) depending on which key is being pressed (up, down, left, right)
- [x] Test in private browser to make sure code is working
- [x] Fix any CSS issues and fix any code errors.
