### ISSUE TITLE
User can start their car

### ISSUE THREAD

**Issue by raymondkhoaho** [raymondkhoaho/driving-game#3]
## 💰 Motivation

It's a driving game, duh!

## 📐 Plan

Move the car a few pixels every 16 milliseconds when the user presses space.

## ✅ Task List

- [x] Add function that starts an interval of 16m and moves it by few pixels.
- [x] Add an addEventListener 'keydown' to the document to invoke above function.
- [x] Clean up any unnecessary CSS and fix any errors in code.
